In [1]:
import numpy as np

In [9]:
arr=np.zeros(10)
arr[5]=1
arr

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [15]:
arr1=np.random.randint(10,49,size=(10))
arr1

array([26, 45, 11, 47, 31, 14, 41, 24, 47, 37])

In [16]:
np.flip(arr1)

array([37, 47, 24, 41, 14, 31, 47, 11, 45, 26])

In [17]:
arr2=np.random.randint(0,8,size=(3,3))
arr2

array([[5, 2, 7],
       [3, 5, 0],
       [3, 0, 0]])

In [21]:
arr3=np.array([1,2,0,0,4,0])
np.nonzero(arr3)


(array([0, 1, 4]),)

In [24]:
np.random.rand(3,3,3)

array([[[0.32770386, 0.19733857, 0.92548409],
        [0.68374914, 0.76184228, 0.70113248],
        [0.699878  , 0.70735942, 0.559383  ]],

       [[0.75402643, 0.66891688, 0.09126076],
        [0.29987854, 0.52686491, 0.48337888],
        [0.63979691, 0.51535993, 0.79933034]],

       [[0.46234512, 0.18468277, 0.66072242],
        [0.13948866, 0.2346317 , 0.74811158],
        [0.47821836, 0.18002332, 0.5956192 ]]])

In [29]:
arr5=np.random.rand(10,10)
arr5

array([[0.23664216, 0.36760349, 0.4686049 , 0.13026618, 0.80113506,
        0.27809579, 0.39898635, 0.87357689, 0.02789867, 0.5429236 ],
       [0.40876643, 0.28367793, 0.96176647, 0.71017798, 0.22646364,
        0.34082344, 0.93890865, 0.3031183 , 0.06622567, 0.41058407],
       [0.01247067, 0.35249231, 0.60728372, 0.7445011 , 0.66212432,
        0.75009244, 0.57443936, 0.15472513, 0.97430763, 0.89076875],
       [0.05096584, 0.2404668 , 0.67975596, 0.4758048 , 0.03470688,
        0.45145309, 0.55837784, 0.35998363, 0.72746799, 0.25636182],
       [0.11910748, 0.69087963, 0.5101969 , 0.20109057, 0.39687218,
        0.95130815, 0.25644435, 0.49549812, 0.02599121, 0.06683265],
       [0.09902296, 0.74565736, 0.67131159, 0.84995001, 0.26741251,
        0.34040163, 0.1770126 , 0.51081066, 0.34614408, 0.93884584],
       [0.78577649, 0.66923955, 0.67176201, 0.82914767, 0.07622401,
        0.04227922, 0.98123305, 0.04708635, 0.43916105, 0.2547255 ],
       [0.1127041 , 0.41729317, 0.0055484

In [30]:
np.min(arr5)

0.005548434621364451

In [31]:
np.max(arr5)

0.9812330542990181

In [45]:
n=3
m=3
arr6=np.zeros((n,m))
arr6

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
arr6[0,:]=1
arr6[:,1]=1
arr6[n-1,:]=1
arr6[:,m-1]=1

In [44]:
arr6

array([[1., 1., 1.],
       [0., 1., 1.],
       [1., 1., 1.]])